from .fabric_api import (cd, hide, settings, show, path, prefix, lcd, quiet, warn_only,
                         remote_tunnel, shell_env, hosts, roles, runs_once, with_settings,
                         task, serial, parallel, require, prompt, put, get, run, sudo, local,
                         reboot, open_shell, output, abort, warn, puts, fastprint, execute)
from .fabric_contrib_api import (rsync_project, upload_project, confirm, exists, is_link, first,
                                 upload_template, sed, uncomment, comment, contains, append)

from .gitlab_ci_context import env
from .fabric_context import Host, Role, Environment, run_per_host, run_per_role

__all__ = [
    "env",
    "cd",
    "hide",
    "settings",
    "show",
    "path",
    "prefix",
    "lcd",
    "quiet",
    "warn_only",
    "remote_tunnel",
    "shell_env",
    "hosts",
    "roles",
    "runs_once",
    "with_settings",
    "task",
    "serial",
    "parallel",
    "require",
    "prompt",
    "put",
    "get",
    "run",
    "sudo",
    "local",
    "reboot",
    "open_shell",
    "output",
    "abort",
    "warn",
    "puts",
    "fastprint",
    "execute",
    "rsync_project",
    "upload_project",
    "confirm",
    "exists",
    "is_link",
    "first",
    "upload_template",
    "sed",
    "uncomment",
    "comment",
    "contains",
    "append",
    "Host",
    "Role",
    "Environment",
    "run_per_host",
    "run_per_role"
]
